// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MusicLesson.Models;

public partial class Duration
{
    [Key]
    public int DurationID { get; set; }

    [Required]
    [StringLength(5)]
    public string Length { get; set; }

    [Column(TypeName = "decimal(18, 0)")]
    public decimal Cost { get; set; }

    [InverseProperty("Duration")]
    public virtual ICollection<Lessons> Lessons { get; } = new List<Lessons>();
}
