// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MusicLesson.Models;

public partial class Instrument
{
    [Key]
    public int InstrumentID { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string InstrumentName { get; set; }

    [InverseProperty("Instrument")]
    public virtual ICollection<Lessons> Lessons { get; } = new List<Lessons>();
}