// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MusicLesson.Models;

[Index("LessonID", Name = "IX_Lessons")]
public partial class Lessons
{
    [Key]
    public int LessonID { get; set; }

    public int StudentID { get; set; }

    public int InstrumentID { get; set; }

    public int TutorID { get; set; }

    public int DurationID { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime LessonDateTime { get; set; }

    public int? LetterID { get; set; }

    [ForeignKey("DurationID")]
    [InverseProperty("Lessons")]
    public virtual Duration Duration { get; set; }

    [ForeignKey("InstrumentID")]
    [InverseProperty("Lessons")]
    public virtual Instrument Instrument { get; set; }

    [ForeignKey("LetterID")]
    [InverseProperty("Lessons")]
    public virtual Letters Letter { get; set; }

    [ForeignKey("StudentID")]
    [InverseProperty("Lessons")]
    public virtual Students Student { get; set; }

    [ForeignKey("TutorID")]
    [InverseProperty("Lessons")]
    public virtual Tutors Tutor { get; set; }
    public int Term { get; set; }

    public int Semester { get; set; }

    [Required]
    [StringLength(4)]
    public string Year { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime TermStartDate { get; set; }
    [NotMapped]
    public bool isChecked { get; set; }
    [NotMapped]
    public virtual Tutors TutorData { get; set; }
    [NotMapped]
    public virtual Students StudentData { get; set; }
    
    [NotMapped]
    public virtual Instrument InstrumentData { get; set; }
    [NotMapped]
    public virtual Duration DurationData { get; set; }
    [NotMapped]
    public virtual Letters? LetterData { get; set; }

}