// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MusicLesson.Models;

public partial class Students
{
    [Key]
    public int StudentID { get; set; }

    [Required]
    [StringLength(200)]
    [Unicode(false)]
    public string FirstName { get; set; }

    [Required]
    [StringLength(400)]
    [Unicode(false)]
    public string LastName { get; set; }

    [DataType(DataType.Date)]
    public DateTime DOB { get; set; }

    [Required]
    [StringLength(200)]
    [Unicode(false)]
    public string Guardian { get; set; }

    [Required]
    [StringLength(100)]
    [EmailAddress]
    public string Email { get; set; }

    [Required]
    [StringLength(11)]
    public string Mobile { get; set; }

    [InverseProperty("Student")]
    public virtual ICollection<Lessons> Lessons { get; } = new List<Lessons>();
}