// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MusicLesson.Models;

public partial class Tutors
{
    [Key]
    public int TutorID { get; set; }

    [Required]
    [StringLength(600)]
    [Unicode(false)]
    public string TutorName { get; set; }

    [InverseProperty("Tutor")]
    public virtual ICollection<Lessons> Lessons { get; } = new List<Lessons>();
}
